# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-19 12:53
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180619_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='geonil', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷 으로', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
