# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='checkcont',
            field=models.CharField(blank=True, default='1.상세페이지:특이사항없음<br> 2.장바구니:특이사항없음<br> 3.옵션기능:특이사항없음', help_text='사이트구조', max_length=100, verbose_name='사이트구조'),
        ),
        migrations.AlterField(
            model_name='review',
            name='checklogin',
            field=models.CharField(blank=True, default='1.바로구매하기:가능<br>2.장바구니:가능', help_text='비회원구매', max_length=100, verbose_name='비회원구매'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fitness',
            field=models.CharField(blank=True, default='상/중/하', help_text='적합도', max_length=10, verbose_name='적합도'),
        ),
        migrations.AlterField(
            model_name='review',
            name='opinion',
            field=models.TextField(blank=True, help_text='검토의견', verbose_name='검토의견'),
        ),
    ]
