# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180712_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='server',
            field=models.TextField(blank=True, help_text='네임서버', max_length=100, verbose_name='네임서버'),
        ),
    ]
